{{ range $k, $v := .Values.services }}
{{ with $v }}
{{ if .autoscaling }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ $k }}
  labels: &labels
    app.kubernetes.io/name: {{ $k }}
    app.kubernetes.io/instance: {{ $k }}-{{ $.Release.Name }}
    app.kubernetes.io/version: {{ $.Chart.Version }}
    app.kubernetes.io/component: {{ .type | default "passthrough" }}
    app.kubernetes.io/part-of: {{ $.Chart.Name }}
    app.kubernetes.io/managed-by: helm
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ $k }}
  minReplicas: {{ .autoscaling.minReplicas | default 1 }}
  maxReplicas: {{ .autoscaling.maxReplicas | default 10 }}
  metrics:
    {{- if .autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}
{{- end }}
{{- end }}
